package gr.teicm.offersaroundws.model.pojos;
// Generated Nov 25, 2014 10:11:27 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Offers generated by hbm2java
 */
public class Offers  implements java.io.Serializable {


     private int offerId;
     private Stores stores;
     private String product;
     private float price;
     private Date beginDate;
     private Date endDate;

    public Offers() {
    }

	
    public Offers(Stores stores, String product, float price, Date endDate) {
        this.stores = stores;
        this.product = product;
        this.price = price;
        this.endDate = endDate;
    }
    public Offers(Stores stores, String product, float price, Date beginDate, Date endDate) {
       this.stores = stores;
       this.product = product;
       this.price = price;
       this.beginDate = beginDate;
       this.endDate = endDate;
    }
   
    public int getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(int offerId) {
        this.offerId = offerId;
    }
    public Stores getStores() {
        return this.stores;
    }
    
    public void setStores(Stores stores) {
        this.stores = stores;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }




}