package gr.teicm.offersaroundws.model.pojos;

/**
 * Offerstemp generated by hbm2java
 */
public class Offerstemp  implements java.io.Serializable {


     private int businessId;
     private String businessName;
     private float latitude;
     private float longitude;
     private String offer;

    public Offerstemp() {
    }

    public Offerstemp(int businessId, String businessName, float latitude, float longitude, String offer) {
        this.businessId = businessId;
        this.businessName = businessName;
        this.latitude = latitude;
        this.longitude = longitude;
        this.offer = offer;
    }
    
    public Offerstemp(String businessName, float latitude, float longitude, String offer) {
       this.businessName = businessName;
       this.latitude = latitude;
       this.longitude = longitude;
       this.offer = offer;
    }
   
    public int getBusinessId() {
        return this.businessId;
    }
    
    public void setBusinessId(int businessId) {
        this.businessId = businessId;
    }
    public String getBusinessName() {
        return this.businessName;
    }
    
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }
    public float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }
    public float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }
    public String getOffer() {
        return this.offer;
    }
    
    public void setOffer(String offer) {
        this.offer = offer;
    }




}


